### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jtarchie** [rouault/sqlite_rtree_bulk_load#1]
Please provide installation instructions on how to use this code.

I spent some time compiling this and trying to load it as an extension. This appears to be meant as a drop-in replacement for rtree, not an extension that also provides rtree functionality.

**Comment by sandman7920** [comment]
This is meant to be used inside of your software.

Typical GPKG spatial index creation with `mod_spatialite`

```sql
SELECT load_extension('mod_spatialite');
SELECT EnableGPKGMode();
SELECT gpkgAddSpatialIndex('mytable', 'geom');
INSERT OR REPLACE INTO "rtree_mytable_geom" SELECT "fid", St_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"),ST_MaxY("geom") FROM mytable;
```

In my case with 29mil point records the example above took ~= **10 minutes**

With code from this repo index creation took ~= **2 minutes**

```C
sqlite_rtree_bl_from_feature_table(
    sqlite_handler,
    "mytable", "fid", "geom", "rtree_mytable_geom",
    "id", "minx", "miny", "maxx", "maxy",
    1024UL * 1024UL * 1536UL, &pszErrMsg, nullptr, nullptr);
```
